export const PHOENIX_BUILD_INFO = {
  id: 'phoenix7-v3n3-living-ecosystem-npc-visuals',
  title: 'Phoenix7 v3N3 — Living Ecosystem + NPC Visual Pass',
  entrypoint: 'v3l.html',
  runtime: 'src/game/v3/',
  launchers: [
    '00_START_HERE_CURRENT_BUILD_WINDOWS.bat',
    'START_GAME_V3L_WINDOWS.bat',
  ],
  versionLine: 'v3L / v3N3',
  dateTag: '2026-06-23',
  features: [
    'current v3L launch path with explicit v3N3 screen marker',
    'v3N2 living world ecosystem: caravans, patrols, ambushes, trade cycle and caravan reward loop',
    'hostile ambushes spawned as monsters so current weapons, ballistics and phase attacks can hit them',
    'v3N3 procedural life NPC visual upgrade: caravans, empire, red peasants, bandits, zhuzher, knights, phase guild, travelers and elementals',
    'v3N3 procedural story NPC visual upgrade: Rina, merchant, clay worker, Oran, Gerda, Sava, smuggler, Tsarbor scout, glass monk, ice ranger and caravan walker',
    'debug commands for caravan ambushes, living world diagnostics and visual-tier inspection',
  ],
  integrationFiles: [
    'v3l.html',
    'src/game/v3/main.js',
    'src/game/v3/buildInfo.js',
    'src/game/v3/data/lifeData.js',
    'src/game/v3/world/life.js',
    'src/game/v3/world/lifeVisuals.js',
    'src/game/v3/world/storyNpcVisuals.js',
    'RUN_CURRENT_BUILD_RU.md',
    'README.md',
    'tools/v3n3_integration_smoke.mjs',
  ],
  browserChecks: [
    'Start screen shows Phoenix7 v3N3',
    'HUD footer shows v3N3 · improved NPC models',
    'J journal contains v3N2 living tract enabled and v3N3 procedural model upgrade entries',
    'PHX_V3_ENGINE.getBuildInfo() returns this manifest',
    'PHX_V3_ENGINE.listLifeVisuals() shows visualTier v3N3_procedural_life_model for upgraded agents',
    'PHX_V3_ENGINE.listStoryNpcVisuals() shows visualTier v3N3_story_npc_model for upgraded story NPCs',
    'PHX_V3_ENGINE.forceNearestCaravanAmbush(\'bandits\') spawns shootable hostile monsters',
    'PHX_V3_ENGINE.forceNearestCaravanAmbush(\'zhuzher\') spawns shootable zhuzher hostile monsters',
  ],
  buildCommands: [
    'npm install',
    'npm run test:v3n3',
    'npm run build',
    'npm run preview',
  ],
  limitations: [
    'Full save serialization is still not connected; localStorage currently stores quality preset only.',
    'Aircraft raids are not part of v3N3; they should be a separate v3N4 pass with proper aerial hitboxes.',
    'NPC visuals are procedural Three.js overlays, not imported skinned assets.',
    'Ambush enemies use monster combat path so weapons work, but faction-vs-faction combat AI is still lightweight.',
  ],
};
