export const ACT1_ROADMAP = {
  updatedAt: '2026-06-24',
  iteration: 'v3P2 Act 1 integrated playable slice — windows + completion + debug + GLM vehicle bridge',
  build: {
    title: 'The elder neuroslops chapter one: Ashgrave',
    subtitle: 'Act 1 Integrated Gameplay Layer Launcher',
    recommended: '/v3p2_ww2_live.html?ww2=1&act1=1',
    branch: 'feat/v3p2-ww2-arsenal-microbuild',
    pr: '#12 draft',
    mergePolicy: 'No blind merge: use this launcher for smoke, then merge only after conflicts/tests are clean.',
  },
  launchTargets: [
    { id: 'act1-live', title: 'Act 1 integrated gameplay build', href: '/v3p2_ww2_live.html?ww2=1&act1=1', primary: true, note: 'Canonical playable slice: староста → road events → встреча → GLM Puma бронецель → crates → return → completion impact.', checks: ['Start opens Act 1 route', 'new HUD visible', 'E opens elder panel', 'draggable windows', 'road events', 'F8 debug labels', 'GLM vehicle target', 'collect crates', 'completion screen'] },
    { id: 'vehicle-lab', title: 'Ashgrave modular vehicle lab', href: '/vehicle_lab.html', note: 'GLM V8 vehicle sandbox converted into local Phoenix7 modules: 10 vehicles, hitboxes, structural damage, rockets, loot.', checks: ['1–0 spawn vehicles', 'R/P rockets', 'T PT-rifle', 'Y MG burst', 'B hitboxes', 'L labels', 'C clear'] },
    { id: 'ww2-live-clean', title: 'WW2 live weapon test', href: '/v3p2_ww2_live.html?ww2=1', note: 'Same live build without act1 marker. Useful for weapon-only checks; press F2 to start route manually.', checks: ['F2 starts route', 'T targets', '9 Bazooka', 'U arsenal', 'R reload', 'V aim'] },
    { id: 'checkpoint-doc', title: 'Locked checkpoint notes', href: '/docs/ACT1_PLAYABLE_SLICE_CHECKPOINT.md', note: 'Text checkpoint for current slice: launch URL, locked loop, integrated modules, smoke checklist, next plan.', checks: ['launch URL', 'locked loop', 'smoke checklist', 'do-not-merge rule'] },
  ],
  statusColumns: [
    { title: 'Playable now', items: [
      'New visible Ashgrave RPG HUD: quest block, location/coords, clock, vitals, weapon card, ammo card, hotbar',
      'Universal draggable/resizable panel shell: inventory, journal, trader, elder and system panels keep saved size/position',
      'Route elder dialogue panel: accept job, turn in crates, trade ammo, repair active firearm, road rumors',
      'First passable Act 1 loop: settlement quest giver table, road marker, road encounter, GLM vehicle, loot crates, return reward',
      'Completion impact: completion screen, route reputation, trader unlock flag, camp flag/guard/salvage visual changes',
      'Enemy debug and cleanup: F8 labels show id/hp/alive/faction/source, F2 clears stale route spawns',
      'Morrowind-style inventory: item icons, character doll, visible slots, drag/drop equip and double-click equip',
      '23 WW2 weapons, fire modes, visible rockets, physical dropped weapons, class weapon progression',
      'Trophy parts from green crates and burned wagon can be sold at the elder/trader panel',
      'Modular GLM V8 vehicle lab plus Act 1 bridge: Puma with hitboxes/parts/wreck in the real route encounter',
      'Road events between camp and vehicle: abandoned crate, road note, injured caravan man, burned wagon',
    ] },
    { title: 'Needs smoke before merge', items: [
      'UI smoke: new HUD visible after Start, old top/bottom HUD hidden, prompt still visible, I/J/U panels usable',
      'Window smoke: drag trader/inventory panel, resize from lower-right handle, double-click header resets, reload keeps layout',
      'Trader smoke: E at elder opens panel, accept job button works, trade ammo buttons work, active firearm repair works',
      'Act1 route smoke: Start → E at camp → accept job → road events → road encounter → clear enemies → stop GLM Puma → collect 3 crates → return → completion screen',
      'Debug smoke: F8 toggles labels; labels show route source; F2 restart removes old enemies/vehicle/crates/events',
      'Vehicle smoke: small arms mostly block, Bazooka/Panzerfaust/PTRD damage hitboxes, destroyed vehicle remains as wreck and enables crates',
      'Inventory smoke: drag weapon to left/right hand, armor to body slot, phase hand to spellHand, double-click equip',
      'Run npm run test:v3p2ww2 and npm run build locally',
    ] },
    { title: 'Do not merge blind', items: ['PR is intentionally draft while Act 1 gameplay layer is still moving fast', 'GitHub currently reported PR #12 as mergeable false before this iteration', 'Current GitHub mergeable status must be rechecked after every commit', 'Resolve main conflicts and stale cache keys before merge', 'Update this roadmap after every meaningful iteration'] },
  ],
  roadmap: [
    { phase: '1. Weapon pack foundation', status: 'done', points: ['WW2 arsenal data', 'ammo types', 'inventory grant kit', 'live launcher controls'] },
    { phase: '2. RPG interface slice', status: 'in-progress', points: ['Ashgrave RPG HUD overhaul installed', 'Morrowind-style inventory installed', 'route elder/trader panel installed', 'draggable/resizable window shell installed', 'next: full barter list and item sale rules'] },
    { phase: '3. Act 1 playable slice', status: 'in-progress', points: ['route loop installed', 'quest journal override', 'road encounter', 'road events', 'GLM vehicle encounter', 'loot crates and turn-in reward', 'completion impact screen and camp dressing', 'checkpoint doc locked'] },
    { phase: '4. Vehicles and anti-vehicle layer', status: 'in-progress', points: ['GLM V8 lab modularized', '10 vehicle silhouettes', 'hitbox/raycast damage', 'Act 1 Puma bridge installed', 'wreck remains after destruction', 'next: richer vehicle loot and secondary blasts in route'] },
    { phase: '5. Physical weapon world', status: 'in-progress', points: ['drop/pickup', 'combat disarm', 'world value', 'rare NPC offers', 'next: NPC crowd behavior around campaigns'] },
    { phase: '6. Debug and stability', status: 'in-progress', points: ['F8 entity labels', 'route spawn source tracking', 'hard cleanup on restart', 'route stage counts only its own entities', 'next: browser smoke and build/test'] },
  ],
  controls: [
    ['Start', 'enter play mode and auto-open Act 1 route if URL has act1=1'], ['F2', 'start/restart playable Act 1 route and clear stale route spawns'], ['F3', 'debug teleport to current route objective'], ['F8', 'toggle enemy/entity debug labels: id, hp, alive, faction/source'], ['J', 'Act 1 route journal'], ['I', 'Morrowind-style inventory / character doll'], ['E', 'quest interaction / road event / pickup / elder panel'], ['1–0', 'quick WW2 weapon switch'], ['H', 'cycle fire mode'], ['R', 'reload / clear jam'], ['V', 'aim mode'], ['U', 'WW2 arsenal menu'], ['N', 'drop active weapon'],
  ],
  nextIteration: [
    'Run local smoke and fix any browser console errors from the integrated route.',
    'Make vehicle destruction loot use real inventory/economy items, not only counters.',
    'Expand trader tier after completion with real named goods and prices.',
    'Add save/load for route stage, dropped weapons, trader state and community campaigns.',
    'Polish NPC yaw-only facing and role-based enemy movement so they stop walking backwards.',
  ],
};
