export const ACT1_ROADMAP = {
  updatedAt: '2026-06-23',
  iteration: 'v3P2 Act 1 gameplay layer — weapon world / race-aware hands pass',
  build: {
    title: 'The elder neuroslops chapter one: Ashgrave',
    subtitle: 'Act 1 Gameplay Layer Launcher',
    recommended: '/v3p2_ww2_live.html?ww2=1&act1=1',
    branch: 'feat/v3p2-ww2-arsenal-microbuild',
    pr: '#12 draft',
    mergePolicy: 'No blind merge: use this launcher for smoke, then merge only after conflicts/tests are clean.',
  },
  launchTargets: [
    {
      id: 'act1-live',
      title: 'Act 1 gameplay live build',
      href: '/v3p2_ww2_live.html?ww2=1&act1=1',
      primary: true,
      note: 'Main working build: WW2 arsenal, physical weapons, vehicle tests, living-world offers.',
      checks: ['Start', 'F1 zones', '1–0 weapons', 'H modes', 'N drop weapon', 'E pickup / talk', 'Y vehicles'],
    },
    {
      id: 'ww2-live-clean',
      title: 'WW2 live weapon test',
      href: '/v3p2_ww2_live.html?ww2=1',
      note: 'Same live build without act1 marker. Useful for weapon-only checks.',
      checks: ['T targets', '9 Bazooka', 'U Panzerfaust/PTRD/Boys AT', 'R reload', 'V aim'],
    },
    {
      id: 'ww2-micro',
      title: 'WW2 arsenal micro data check',
      href: '/tools/v3p2_ww2_micro_build.html',
      note: 'Fast browser page for data sanity, not the full RPG layer.',
      checks: ['23 weapons', '12 ammo types', 'icons', 'roles'],
    },
    {
      id: 'legacy-v3l',
      title: 'Legacy v3L reference build',
      href: '/v3l.html',
      note: 'Reference page for old weapon/hands feel if something regresses.',
      checks: ['old viewmodel', 'old HUD', 'old inventory flow'],
    },
  ],
  statusColumns: [
    {
      title: 'Playable now',
      items: [
        '23 WW2 weapons wired into arsenal/inventory/ammo',
        'SEMI / BURST×3 / AUTO modes on automatic firearms',
        'Visible ballistic rockets for Bazooka/Panzerfaust with direct + splash damage',
        'Large visible vehicle targets and armor blocking for normal bullets',
        'Physical dropped weapons: N drop, E pickup, combat disarm chance',
        'NPCs notice valuable weapons, make offers, and start community fund campaigns if refused',
        'Weapon viewmodel polish pass: moving bolts/slides/pumps/belts/rockets and ejected casings',
        'Race-aware first-person arms and reload poses',
      ],
    },
    {
      title: 'Needs smoke before merge',
      items: [
        'Browser smoke for all quick weapons 1–0 after latest race-aware hands pass',
        'Check reload poses for human/deimur/reptiloid/tsarbor profiles',
        'Check dropped weapon pickup after switching hands and after combat disarm',
        'Check NPC offer panel does not conflict with normal talk/interact prompt',
        'Check vehicle target stability after Y/T spawn and rocket impacts',
        'Run npm run test:v3p2ww2 and npm run build locally',
      ],
    },
    {
      title: 'Do not merge blind',
      items: [
        'PR is intentionally draft while Act 1 gameplay layer is still moving fast',
        'Current GitHub mergeable status must be rechecked after every commit',
        'Resolve main conflicts and stale cache keys before merge',
        'Update this roadmap after every meaningful iteration',
      ],
    },
  ],
  roadmap: [
    {
      phase: '1. Weapon pack foundation',
      status: 'done',
      points: ['WW2 arsenal data', 'ammo types', 'inventory grant kit', 'live launcher controls'],
    },
    {
      phase: '2. Combat feel',
      status: 'in-progress',
      points: ['fire modes', 'stamina tuning', 'recoil feel', 'procedural audio', 'armor blocked feedback still needs polish'],
    },
    {
      phase: '3. Vehicles and anti-vehicle layer',
      status: 'in-progress',
      points: ['large test vehicles visible', 'vehicle armor', 'rocket direct/splash damage', 'geometry/locomotion still needs another art pass'],
    },
    {
      phase: '4. Physical weapon world',
      status: 'in-progress',
      points: ['drop/pickup', 'combat disarm', 'world value', 'NPC offers', 'community fund campaigns', 'next: NPC crowd behavior around campaigns'],
    },
    {
      phase: '5. Weapon models and animations',
      status: 'in-progress',
      points: ['first polish layer for model details', 'moving parts', 'race-aware hands', 'next: family-specific hand choreography and third-person carried weapons'],
    },
    {
      phase: '6. Act 1 gameplay completeness',
      status: 'next',
      points: ['zone placement', 'quest hooks', 'traders/stashes', 'loot economy', 'enemy loadout balance', 'save/load for dropped weapons and campaigns'],
    },
  ],
  controls: [
    ['Start', 'enter play mode'],
    ['F1', 'jump through debug zones'],
    ['1–0', 'quick WW2 weapon switch'],
    ['H', 'cycle fire mode'],
    ['Hold LMB', 'AUTO fire if supported'],
    ['R', 'reload / clear jam'],
    ['V', 'aim mode'],
    ['U', 'WW2 arsenal menu'],
    ['G', 'restock kit/ammo'],
    ['T', 'targets + large vehicles'],
    ['Y', 'large vehicles only'],
    ['N', 'drop active weapon'],
    ['E', 'pickup dropped weapon / discuss weapon offer near NPC'],
  ],
  nextIteration: [
    'Family-specific hand choreography: magazine reload, pump, break-open, belt-feed, launcher reload.',
    'NPC crowd behavior for weapon campaigns: gather, chant, fund ticks, settlement event marker.',
    'Dropped weapons noticed by NPCs on the ground, with pickup/claim behavior.',
    'Act 1 economy pass: where rare guns appear, who can afford them, who fears them.',
  ],
};
