import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.166.1/build/three.module.js';
const BUILD='Phoenix7 2.0A GitHub Rebuild / Port Rachel', SAVE='phoenix7_v2_save';
const $=id=>document.getElementById(id);
const ui={start:$('startScreen'),char:$('charScreen'),hud:$('hud'),qT:$('questTitle'),qX:$('questText'),qD:$('questDistance'),prompt:$('prompt'),toast:$('toast'),book:$('bookWindow'),bookC:$('bookContent'),map:$('mapWindow'),mapC:$('mapCanvas'),dlg:$('dialogueWindow'),dlgN:$('dialogueName'),dlgT:$('dialogueText'),dlgC:$('dialogueChoices')};
const canvas=$('gameCanvas');
const races={human:['Человек Империи',112,105],red:['Красный элементал',126,95],blue:['Синий элементал',104,112],phase:['Задетый фазой',96,120]};
const pois=[['port','Порт Рейчел',-230,38,'мокрый причал и пустое дело'],['road','Дорога Синего Шельфа',-130,28,'дорога к Форту Заря'],['beacon','Старый маяк',-62,18,'маяк прошлого цикла'],['gate','Ворота Форта Заря',36,10,'южные ворота'],['office','Канцелярия Форта Заря',74,-4,'Оран Тив ставит печати'],['shed','Дорожный навес',-182,-18,'мокрые ящики и верёвка']];
const npcs=[
 {id:'dock',n:'Портовый рабочий Лейб',x:-238,z:50,c:0xb48a52,t:'Транспорт ушёл. Если твоего имени нет в бумагах — иди в Форт Заря. Там любят пустые дела.',ch:[['Где Форт Заря?','По дороге на северо-восток. Держись фонарей и старого маяка.']]},
 {id:'clerk',n:'Таможенный клерк Рина',x:-218,z:28,c:0x8ca3bf,t:'В твоей карточке есть номер, но нет причины прибытия. Кто-то оставил тебя между полями формы.',ch:[['Что делать?','Оран Тив в Форту Заря ставит печати на такие ошибки. Потом тебя заметит Герда.']]},
 {id:'guard',n:'Солдат у дороги',x:-98,z:26,c:0x71826f,t:'Дорога открыта. У старого маяка иногда слышат синий звон.',ch:[['Что за звон?','Синие рыцари говорят — музыка. Зелёные говорят — системная ошибка. Я говорю: не стой рядом ночью.']]},
 {id:'oran',n:'Писарь Оран Тив',x:74,z:-4,c:0xd8b56e,t:'Фамилия отсутствует, причина этапирования отсутствует, подпись есть. Прекрасно. Пустое дело.',ch:[['Получить регистрацию','Печать поставлена. Теперь ты существуешь достаточно, чтобы тебя отправили к Герде.', 'register']]},
 {id:'gerda',n:'Герда Гайгерманика',x:98,z:-22,c:0x795c43,t:'Пустые дела редко бывают пустыми. В 2.0B здесь начнётся мой настоящий актовый узел.',ch:[['Я понял','Хорошо. Для начала выживи на дороге.']]}
];
let state={mode:'menu',player:null,keys:new Set(),yaw:Math.PI/2,pitch:0,nearest:null,blockers:[],npcObj:[],labels:[],last:0};
const sfx=audio();
const renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio||1,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x15120d); scene.fog=new THREE.Fog(0x211b13,70,320);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,520), yawPivot=new THREE.Object3D(), pitchPivot=new THREE.Object3D(); yawPivot.add(pitchPivot); pitchPivot.add(camera); camera.position.set(0,1.72,0); scene.add(yawPivot);
scene.add(new THREE.HemisphereLight(0xdac99b,0x2e302f,1.05)); const sun=new THREE.DirectionalLight(0xffd18a,1.9); sun.position.set(-38,64,25); sun.castShadow=true; scene.add(sun); const moon=new THREE.DirectionalLight(0x93a6c7,.45); moon.position.set(55,20,-40); scene.add(moon);
makeWorld(); startMenu(); requestAnimationFrame(loop); addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.9});}
function mesh(g,m,x,y,z){const o=new THREE.Mesh(g,m); o.position.set(x,y,z); o.castShadow=o.receiveShadow=true; scene.add(o); return o;}
function makeWorld(){
 const ground=mesh(new THREE.PlaneGeometry(520,360,12,12),mat(0x40382a),0,0,0); ground.rotation.x=-Math.PI/2;
 const water=mesh(new THREE.PlaneGeometry(260,180),new THREE.MeshStandardMaterial({color:0x1f3440,roughness:.55,metalness:.1,transparent:true,opacity:.74}),-275,.03,80); water.rotation.x=-Math.PI/2;
 road(-225,38,110,10,.05); road(-128,30,95,9,-.08); road(-40,18,90,9,-.12); road(35,8,70,10,-.16); pier(-242,58,36,8);
 house(-214,28,12,9,8,0x57452e,'Таможня'); house(-198,8,10,8,8,0x4b3d2c,'Склад'); house(-188,-20,14,10,7,0x665138,'Дорожный навес'); house(40,7,16,12,11,0x5a4a35,'Ворота'); house(74,-4,16,10,9,0x6a5538,'Канцелярия'); house(98,-22,12,10,8,0x49382b,'Дом Герды'); wall(26,20,74,4); wall(32,-34,78,4); wall(-12,-7,4,52); wall(116,-7,4,58); beacon(-62,18);
 for(let i=0;i<70;i++) rock(-250+Math.random()*390,-80+Math.random()*150,.5+Math.random()*1.8); for(let i=0;i<18;i++) crate(-230+Math.random()*44,18+Math.random()*48); for(let i=0;i<14;i++) lamp(-220+i*21,35+Math.sin(i*.8)*7);
 pois.forEach(p=>marker(p[2],p[3],p[1],p[0]==='gate'||p[0]==='office'?0xd8b56e:0x88a6c9)); npcs.forEach(addNpc);
}
function road(x,z,l,w,r){const o=mesh(new THREE.BoxGeometry(l,.08,w),mat(0x6a5b42),x,.04,z); o.rotation.y=r;}
function pier(x,z,l,w){const d=mesh(new THREE.BoxGeometry(l,.45,w),mat(0x4a3323),x,.25,z); for(let i=-2;i<=2;i++)mesh(new THREE.CylinderGeometry(.35,.45,2.6,8),mat(0x2e2118),x+i*7,1.15,z+w*.55);}
function house(x,z,w,d,h,c,name){mesh(new THREE.BoxGeometry(w,h,d),mat(c),x,h/2,z); const roof=mesh(new THREE.ConeGeometry(Math.max(w,d)*.72,h*.34,4),mat(0x2b2219),x,h+h*.18,z); roof.rotation.y=Math.PI/4; state.blockers.push({x,z,w:w+2,d:d+2}); label(name,x,h+2.2,z);}
function wall(x,z,w,d){mesh(new THREE.BoxGeometry(w,7,d),mat(0x3a3024),x,3.5,z); state.blockers.push({x,z,w:w+1,d:d+1});}
function beacon(x,z){mesh(new THREE.CylinderGeometry(.55,.9,9,8),mat(0x2f3e38),x,4.5,z); const top=mesh(new THREE.IcosahedronGeometry(2.2,0),new THREE.MeshStandardMaterial({color:0x76b38d,roughness:.3,emissive:0x122318,emissiveIntensity:.9}),x,10,z); label('Старый маяк',x,13,z);}
function rock(x,z,s){const o=mesh(new THREE.DodecahedronGeometry(s,0),mat(0x37342d),x,s*.45,z); o.rotation.set(Math.random(),Math.random(),Math.random());}
function crate(x,z){const o=mesh(new THREE.BoxGeometry(2.1,1.6,2.1),mat(0x5d432c),x,.8,z); o.rotation.y=Math.random()*Math.PI;}
function lamp(x,z){mesh(new THREE.CylinderGeometry(.12,.16,3,6),mat(0x211914),x,1.5,z); mesh(new THREE.SphereGeometry(.42,8,8),new THREE.MeshStandardMaterial({color:0xffc45f,emissive:0xff8a24,emissiveIntensity:1.1}),x,3.1,z); const l=new THREE.PointLight(0xffb45f,1.2,18); l.position.set(x,3.2,z); scene.add(l);}
function marker(x,z,name,c){const r=new THREE.Mesh(new THREE.TorusGeometry(2.2,.08,8,32),new THREE.MeshBasicMaterial({color:c})); r.position.set(x,.12,z); r.rotation.x=Math.PI/2; scene.add(r); label(name,x,2.2,z);}
function addNpc(n){const g=new THREE.Group(); g.add(new THREE.Mesh(new THREE.CylinderGeometry(.75,.9,2.4,10),mat(n.c))); g.children[0].position.y=1.2; const h=new THREE.Mesh(new THREE.SphereGeometry(.55,12,10),mat(0xc9a982)); h.position.y=2.65; const q=new THREE.Mesh(new THREE.OctahedronGeometry(.32,0),new THREE.MeshStandardMaterial({color:0xffdd7a,emissive:0x332000,emissiveIntensity:.8})); q.position.y=3.65; g.add(h,q); g.position.set(n.x,0,n.z); g.userData.npc=n; scene.add(g); label(n.n,n.x,4.2,n.z); state.npcObj.push(g);}
function label(text,x,y,z){const c=document.createElement('canvas'); c.width=512;c.height=96; const g=c.getContext('2d'); g.fillStyle='rgba(10,8,5,.72)';g.fillRect(0,0,512,96);g.strokeStyle='rgba(216,181,110,.55)';g.strokeRect(3,3,506,90);g.fillStyle='#f0dfbd';g.font='700 28px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText(text,256,48); const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false})); sp.position.set(x,y,z);sp.scale.set(10,1.85,1);sp.renderOrder=10;scene.add(sp);state.labels.push(sp);}
function player(opts={}){const r=races[opts.race||'human']||races.human;return{name:opts.name||'Безымянный ссыльный',race:opts.race||'human',bg:opts.bg||'lunar-prisoner',pos:{x:-230,z:38,yaw:Math.PI/2,pitch:0},stats:{hp:r[1],st:r[2],level:1,xp:0,credits:12},flags:{registered:false},quest:{step:'road',done:false},book:{events:[evt('world','Ты проснулся на мокром причале Порта Рейчел. В бумагах — пустое место.'),evt('quest','Квест начат: Порт Рейчел: пустое дело.')],places:['port'],factions:{empire:'Империя Земли держит Феникс 7 через форты, печати и долги.'}}};}
function evt(type,text){return{t:Date.now(),type,text};}
function startGame(p=player()){state.player=p; state.yaw=p.pos.yaw; state.pitch=p.pos.pitch; yawPivot.position.set(p.pos.x,0,p.pos.z); yawPivot.rotation.y=state.yaw; pitchPivot.rotation.x=state.pitch; ui.start.classList.add('hidden');ui.char.classList.add('hidden');ui.hud.classList.remove('hidden');state.mode='play';sfx.drone(); log('system',`Билд запущен: ${BUILD}`); toast('Ты проснулся в Порту Рейчел. Найди дорогу к Форту Заря.'); updateQuest(); save();}
function startMenu(){ui.start.classList.remove('hidden');ui.char.classList.add('hidden');ui.hud.classList.add('hidden');sfx.stop();}
function quest(){if(!state.player)return null; if(state.player.quest.done)return{title:'Регистрация получена',text:'Ты получил регистрацию. Теперь можно искать Герду.',target:npcs.find(n=>n.id==='gerda')}; if(state.player.quest.step==='oran')return{title:'Порт Рейчел: пустое дело',text:'Найди писаря Орана Тива в канцелярии Форта Заря.',target:npcs.find(n=>n.id==='oran')}; return{title:'Порт Рейчел: пустое дело',text:'Иди по дороге Синего Шельфа к Форту Заря.',target:{x:36,z:10,n:'Ворота Форта Заря'}};}
function updateQuest(){const q=quest();if(!q)return;ui.qT.textContent=q.title;ui.qX.textContent=q.text;ui.qD.textContent=q.target?`Цель: ${q.target.n||q.target.name} · ${Math.round(dist(q.target.x,q.target.z))} м`:'';}
function dist(x,z){return Math.hypot(yawPivot.position.x-x,yawPivot.position.z-z);}
function loop(t){const dt=Math.min(.05,(t-state.last)/1000||.016);state.last=t;if(state.mode==='play')tick(dt);renderer.render(scene,camera);requestAnimationFrame(loop);}
function tick(dt){const m=new THREE.Vector3(); if(state.keys.has('KeyW'))m.z--; if(state.keys.has('KeyS'))m.z++; if(state.keys.has('KeyA'))m.x--; if(state.keys.has('KeyD'))m.x++; if(m.lengthSq()){m.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),state.yaw); const old=yawPivot.position.clone(),spd=(state.keys.has('ShiftLeft')||state.keys.has('ShiftRight'))?13:7; yawPivot.position.x+=m.x*spd*dt;yawPivot.position.z+=m.z*spd*dt;if(hit(yawPivot.position.x,yawPivot.position.z))yawPivot.position.copy(old); discover();} npcPrompt(); progress(); updateQuest();}
function hit(x,z){return state.blockers.some(b=>Math.abs(x-b.x)<b.w/2+.7&&Math.abs(z-b.z)<b.d/2+.7);}
function discover(){for(const p of pois){if(state.player.book.places.includes(p[0]))continue;if(dist(p[2],p[3])<16){state.player.book.places.push(p[0]);log('place',`Открыто место: ${p[1]}.`);sfx.quest();toast(`Открыто место: ${p[1]}`);}}}
function progress(){if(!state.player||state.player.quest.done)return;if(state.player.quest.step==='road'&&dist(36,10)<22){state.player.quest.step='oran';log('quest','Ты дошёл до ворот Форта Заря. Теперь найди писаря Орана Тива.');sfx.quest();}}
function npcPrompt(){state.nearest=null;let best=99;for(const o of state.npcObj){const n=o.userData.npc,d=dist(n.x,n.z); if(d<best&&d<4.2){best=d;state.nearest=n;} o.lookAt(camera.position.clone().add(yawPivot.position));} if(state.nearest){ui.prompt.textContent=`E — говорить: ${state.nearest.n}`;ui.prompt.classList.remove('hidden');}else ui.prompt.classList.add('hidden');}
function dialog(n){state.mode='dialogue';ui.dlgN.textContent=n.n;ui.dlgT.innerHTML=`<p>${n.t}</p>`;ui.dlgC.innerHTML='';for(const c of n.ch){const b=document.createElement('button');b.textContent=c[0];b.onclick=()=>{sfx.ui();ui.dlgT.innerHTML+=`<p><b>${state.player.name}:</b> ${c[0]}</p><p><b>${n.n}:</b> ${c[1]}</p>`;if(c[2]==='register')register();b.disabled=true;};ui.dlgC.appendChild(b);}const end=document.createElement('button');end.textContent='Закончить разговор';end.onclick=()=>close(ui.dlg);ui.dlgC.appendChild(end);ui.dlg.classList.remove('hidden');log('npc',`Разговор: ${n.n}.`);}
function register(){if(state.player.flags.registered)return;state.player.flags.registered=true;state.player.quest.done=true;state.player.stats.credits+=12;state.player.stats.xp+=20;log('quest','Квест завершён: Порт Рейчел: пустое дело. Получена временная регистрация ссыльного.');sfx.done();toast('Регистрация получена. Герда теперь следующая цель.');save();}
function log(type,text){state.player?.book.events.unshift(evt(type,text));if(state.player?.book.events.length>120)state.player.book.events.pop();}
function openBook(tab='events'){if(!state.player)return;sfx.book();state.mode='window';ui.book.classList.remove('hidden');renderBook(tab);}
function renderBook(tab){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const p=state.player;if(tab==='events')ui.bookC.innerHTML=p.book.events.map(e=>`<div class="logEntry"><small>${new Date(e.t).toLocaleTimeString()} · ${e.type}</small><br>${e.text}</div>`).join('');if(tab==='quests'){const q=quest();ui.bookC.innerHTML=`<h3>Порт Рейчел: пустое дело</h3><p>${q.text}</p><p>${p.quest.done?'Статус: завершён.':'Статус: активно.'}</p>`;}if(tab==='places')ui.bookC.innerHTML=p.book.places.map(id=>{const p=pois.find(x=>x[0]===id);return`<div class="logEntry"><span class="poiName">${p?.[1]||id}</span><br>${p?.[4]||''}</div>`;}).join('');if(tab==='factions')ui.bookC.innerHTML=`<div class="logEntry"><span class="poiName">Империя</span><br>${p.book.factions.empire}</div><div class="logEntry"><span class="poiName">Ордены рыцарей</span><br>Зелёные служат Богине Системных Ошибок, синие — Богине Звука. В 2.0A они пока упомянуты.</div>`;}
function openMap(){if(!state.player)return;sfx.page();state.mode='window';ui.map.classList.remove('hidden');drawMap();}
function drawMap(){const ctx=ui.mapC.getContext('2d');ctx.clearRect(0,0,620,420);ctx.fillStyle='#15130f';ctx.fillRect(0,0,620,420);ctx.strokeStyle='rgba(216,181,110,.2)';for(let x=0;x<620;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,420);ctx.stroke();}for(let y=0;y<420;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(620,y);ctx.stroke();}const tm=(x,z)=>[310+x*1.25,210+z*1.25];ctx.strokeStyle='#786342';ctx.lineWidth=10;ctx.lineCap='round';ctx.beginPath();[[-230,38],[-130,28],[-62,18],[36,10],[74,-4]].forEach(([x,z],i)=>{const [mx,my]=tm(x,z);i?ctx.lineTo(mx,my):ctx.moveTo(mx,my);});ctx.stroke();for(const p of pois){const[mx,my]=tm(p[2],p[3]);ctx.fillStyle=state.player.book.places.includes(p[0])?'#d8b56e':'#59616a';ctx.beginPath();ctx.arc(mx,my,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e9dcc4';ctx.font='12px system-ui';ctx.fillText(p[1],mx+9,my+4);}const[px,py]=tm(yawPivot.position.x,yawPivot.position.z);ctx.fillStyle='#92d3ff';ctx.beginPath();ctx.arc(px,py,7,0,Math.PI*2);ctx.fill();ctx.fillText('Ты',px+10,py-8);}
function close(w){w.classList.add('hidden');if(ui.book.classList.contains('hidden')&&ui.map.classList.contains('hidden')&&ui.dlg.classList.contains('hidden'))state.mode='play';}
function toast(t){ui.toast.textContent=t;ui.toast.classList.remove('hidden');clearTimeout(ui.toast._t);ui.toast._t=setTimeout(()=>ui.toast.classList.add('hidden'),3600);}
function save(){if(!state.player)return;state.player.pos.x=yawPivot.position.x;state.player.pos.z=yawPivot.position.z;state.player.pos.yaw=state.yaw;state.player.pos.pitch=state.pitch;localStorage.setItem(SAVE,JSON.stringify({build:BUILD,player:state.player,savedAt:Date.now()}));}
function load(){try{const d=JSON.parse(localStorage.getItem(SAVE)||'{}');if(!d.player)return toast('Сейв 2.0 не найден.');startGame(d.player);}catch{toast('Сейв повреждён.');}}
function audio(){let ctx,master,dr;const ensure=()=>{if(ctx)return ctx;const A=AudioContext||webkitAudioContext;ctx=new A();master=ctx.createGain();master.gain.value=.55;master.connect(ctx.destination);return ctx};const tone=(f,d=.1,type='sine',v=.1,w=0)=>{const c=ensure(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(0,c.currentTime+w);g.gain.linearRampToValueAtTime(v,c.currentTime+w+.01);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+w+d);o.connect(g);g.connect(master);o.start(c.currentTime+w);o.stop(c.currentTime+w+d+.02)};return{unlock(){const c=ensure();if(c.state==='suspended')c.resume()},ui(){tone(420,.07,'triangle',.12);tone(210,.09,'sine',.05,.015)},start(){tone(90,.55,'sawtooth',.06);tone(180,.8,'sine',.09,.06)},book(){tone(160,.16,'triangle',.11)},page(){tone(510,.06,'triangle',.05)},quest(){tone(520,.12,'triangle',.12);tone(260,.14,'sine',.08,.1)},done(){tone(220,.2,'sine',.09);tone(330,.26,'triangle',.09,.12);tone(440,.36,'triangle',.08,.28)},drone(){const c=ensure();if(dr)return;const g=c.createGain();g.gain.value=.025;g.connect(master);const o1=c.createOscillator(),o2=c.createOscillator();o1.frequency.value=55;o2.frequency.value=82.5;o1.connect(g);o2.connect(g);o1.start();o2.start();dr={o1,o2,g}},stop(){if(dr){dr.o1.stop();dr.o2.stop();dr.g.disconnect();dr=null}}};}
$('newGameBtn').onclick=()=>{sfx.ui();ui.char.classList.remove('hidden')};$('quickStartBtn').onclick=()=>{sfx.unlock();sfx.start();localStorage.removeItem(SAVE);startGame(player())};$('continueBtn').onclick=()=>{sfx.ui();load()};$('closeCharBtn').onclick=()=>{sfx.ui();ui.char.classList.add('hidden')};$('startCreatedBtn').onclick=()=>{sfx.unlock();sfx.start();localStorage.removeItem(SAVE);startGame(player({name:$('charName').value.trim()||'Безымянный ссыльный',race:$('raceSelect').value,bg:$('backgroundSelect').value}))};
canvas.onclick=()=>{sfx.unlock();if(state.mode==='play')canvas.requestPointerLock?.()};document.onpointerlockchange=()=>{};document.onmousemove=e=>{if(document.pointerLockElement!==canvas||state.mode!=='play')return;state.yaw-=e.movementX*.0022;state.pitch=Math.max(-1.25,Math.min(1.25,state.pitch-e.movementY*.002));yawPivot.rotation.y=state.yaw;pitchPivot.rotation.x=state.pitch};document.onkeydown=e=>{state.keys.add(e.code);if(e.code==='KeyE'&&state.mode==='play'&&state.nearest){sfx.ui();dialog(state.nearest)}if(e.code==='KeyJ'){e.preventDefault();ui.book.classList.contains('hidden')?openBook():close(ui.book)}if(e.code==='KeyM'){e.preventDefault();ui.map.classList.contains('hidden')?openMap():close(ui.map)}if(e.code==='Escape'){[ui.book,ui.map,ui.dlg].forEach(w=>!w.classList.contains('hidden')&&close(w))}};document.onkeyup=e=>state.keys.delete(e.code);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{sfx.ui();close($(b.dataset.close))});document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{sfx.page();renderBook(b.dataset.tab)});addEventListener('beforeunload',save);setInterval(save,12000);console.log(BUILD);
